### ISSUE TITLE
Responsive navbar

### ISSUE THREAD

**Issue by Kilanga** [RandyyPham/Eastern-Eats#1]
Hello,

You can do a responsive navbar for small screen. You can do it with https://www.w3schools.com/howto/howto_js_topnav_responsive.asp

I have tested it in your code and it work, just a problem with your "ul" list.

I can do it for you today if you want to share your project.

Kind regards

**Comment by RandyyPham** [comment]
Hi,
Okay, I have sent an invite to be a collaborator to my repository.
Alternatively, I have the invite link here: https://github.com/RandyyPham/Eastern-Eats/invitations
This is my first website that I'm making for my class, so any help is very appreciated.
Thank you! :)

**Comment by Kilanga** [comment]
That's so nice.

I'm not a pro, rather a beginner.

I will do my best to help you.
